# Generated by Django 5.2.5 on 2026-04-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emp_id', models.IntegerField()),
                ('designation', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
                ('experience', models.IntegerField()),
            ],
        ),
    ]
